// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.Chip = (function(_super) {
  __extends(Chip, _super);

  function Chip() {
    return Chip.__super__.constructor.apply(this, arguments);
  }

  Chip.prototype.initialize = function(params) {
    return this.set({
      value: params
    });
  };

  return Chip;

})(Backbone.Model);
