// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ChipsCollection = (function(_super) {
    __extends(ChipsCollection, _super);

    function ChipsCollection() {
      return ChipsCollection.__super__.constructor.apply(this, arguments);
    }

    ChipsCollection.prototype.model = Chip;

    ChipsCollection.prototype.initialize = function() {
      return this.add([new Chip(5), new Chip(10)]);
    };

    ChipsCollection.prototype.point = function() {
      var points;
      points = this.reduce(function(points, chip) {
        return points + chip.get('value');
      }, 0);
      return points;
    };

    ChipsCollection.prototype.getNumOfChips = function(chipValue) {
      var num;
      num = this.reduce(function(count, chip) {
        return count + (chip.get('value') === chipValue ? 1 : 0);
      }, 0);
      return num;
    };

    return ChipsCollection;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=ChipsCollection.map
